require 'hoe'
require './lib/factbook-fields/version.rb'


Hoe.spec 'factbook-fields' do

  self.version = Factbook::Module::Fields::VERSION

  self.summary = 'factbook-fields - world factbook country profile meta data - categories, fields, subfields, and more'
  self.description = summary

  self.urls = { home: 'https://github.com/factbook/factbook' }

  self.author = 'Gerald Bauer'
  self.email  = 'openmundi@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
    ['factbook-codes' ],
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
   required_ruby_version: '>= 2.2.2'
  }

end
